<?php 
/*
 * EngagementSummaryAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/02/2016
 */

namespace EngagementSummaryAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Contact extends Customer implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $number public property
     */
    public $number;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $email public property
     */
    public $email;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $name     Initialization value for the property $this->name  
     * @param   string            $number   Initialization value for the property $this->number
     * @param   string            $email    Initialization value for the property $this->email 
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->name   = func_get_arg(0);
            $this->number = func_get_arg(1);
            $this->email  = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']   = $this->name;
        $json['number'] = $this->number;
        $json['email']  = $this->email;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}