<?php 
/*
 * EngagementSummaryAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/02/2016
 */

namespace EngagementSummaryAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Customer extends Engagement implements JsonSerializable {
    /**
     * @todo Write general description for this property
     * @required
     * @var Contact $contact public property
     */
    public $contact;

    /**
     * @todo Write general description for this property
     * @var string $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @var string $industry public property
     */
    public $industry;

    /**
     * Constructor to set initial or default values of member properties
     * @param   Contact           $contact    Initialization value for the property $this->contact 
     * @param   string            $name       Initialization value for the property $this->name    
     * @param   string            $industry   Initialization value for the property $this->industry
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->contact  = func_get_arg(0);
            $this->name     = func_get_arg(1);
            $this->industry = func_get_arg(2);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['contact']  = $this->contact;
        $json['name']     = $this->name;
        $json['industry'] = $this->industry;
        $json = array_merge($json, parent::jsonSerialize());

        return $json;
    }
}