<?php 
/*
 * EngagementSummaryAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/02/2016
 */

namespace EngagementSummaryAPILib\Models;

use JsonSerializable;

/**
 * Engagement Model
 */
class Engagement implements JsonSerializable {
    /**
     * id
     * @required
     * @var integer $id public property
     */
    public $id;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $href public property
     */
    public $href;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $dateOfContact public property
     */
    public $dateOfContact;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $startDate public property
     */
    public $startDate;

    /**
     * @todo Write general description for this property
     * @required
     * @var integer $durationInDays public property
     */
    public $durationInDays;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $keywords public property
     */
    public $keywords;

    /**
     * @todo Write general description for this property
     * @required
     * @var string $summary public property
     */
    public $summary;

    /**
     * @todo Write general description for this property
     * @required
     * @var Customer $customer public property
     */
    public $customer;

    /**
     * @todo Write general description for this property
     * @required
     * @var ProofOfConcept $proofOfConcept public property
     */
    public $proofOfConcept;

    /**
     * Constructor to set initial or default values of member properties
     * @param   integer           $id               Initialization value for the property $this->id            
     * @param   string            $href             Initialization value for the property $this->href          
     * @param   string            $dateOfContact    Initialization value for the property $this->dateOfContact 
     * @param   string            $startDate        Initialization value for the property $this->startDate     
     * @param   integer           $durationInDays   Initialization value for the property $this->durationInDays
     * @param   string            $keywords         Initialization value for the property $this->keywords      
     * @param   string            $summary          Initialization value for the property $this->summary       
     * @param   Customer          $customer         Initialization value for the property $this->customer      
     * @param   ProofOfConcept    $proofOfConcept   Initialization value for the property $this->proofOfConcept
     */
    public function __construct()
    {
        switch(func_num_args())      
        {
            case 9:
                $this->id             = func_get_arg(0);
                $this->href           = func_get_arg(1);
                $this->dateOfContact  = func_get_arg(2);
                $this->startDate      = func_get_arg(3);
                $this->durationInDays = func_get_arg(4);
                $this->keywords       = func_get_arg(5);
                $this->summary        = func_get_arg(6);
                $this->customer       = func_get_arg(7);
                $this->proofOfConcept = func_get_arg(8);
                break;

            default:
                $this->id = 1;
                break;
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']             = $this->id;
        $json['href']           = $this->href;
        $json['dateOfContact']  = $this->dateOfContact;
        $json['startDate']      = $this->startDate;
        $json['durationInDays'] = $this->durationInDays;
        $json['keywords']       = $this->keywords;
        $json['summary']        = $this->summary;
        $json['customer']       = $this->customer;
        $json['proofOfConcept'] = $this->proofOfConcept;

        return $json;
    }
}