<?php
/*
 * EngagementSummaryAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 11/02/2016
 */

namespace EngagementSummaryAPILib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class. 
 */
class Configuration {
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'http://ms3-engagement-summary-api.cloudhub.io';

}
